import 'package:animate_do/animate_do.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:mapbox_flutter/src/bloc/map/map_bloc.dart';
import 'package:mapbox_flutter/src/bloc/location/my_location_bloc.dart';
import 'package:mapbox_flutter/src/bloc/search/search_bloc.dart';
import 'package:mapbox_flutter/src/helpers/helpers.dart';
import 'package:mapbox_flutter/src/models/search_result.dart';
import 'package:mapbox_flutter/src/search/search_destination.dart';
import 'package:mapbox_flutter/src/services/traffic_service.dart';
import 'package:polyline/polyline.dart' as Poly;
part 'btn_location.dart';
part 'btn_my_route.dart';
part 'btn_follow_location.dart';
part 'searchbar_widget.dart';
part 'pinned_manual.dart';